ailibaba:
  durid:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123
    maxActive: 20
    maxWait: 10000
    minIdle: 3
    validationQuery: SELECT 'x'
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    borrowConnectionTimeout: 30000

server:
  port: 8887
spring:
  freemarker:
    request-context-attribute: request
    suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: life.manong.community.entity
  config-location: classpath:mybatis-config.xml
logging:
  file: ./log/mylog.log
  level:
    com.yuan: debug
    org.mybatis: debug